### PR TITLE
Fix/waystone lag fix

### LINKED ISSUE #72: SMWaystones.checkWaystoneExists appears to halt on waiting for the SQL DB

### PR DESCRIPTION
**Pull request by ProjectHSI**
add waystone lag prevention through config + general coding optimization.

### CODE REVIEW

File: src/main/java/com/stemcraft/feature/SMWaystones.java [hunk 1]
```diff
@@ -227,7 +232,14 @@ private void updateWaystoneForLocation(Location location) throws SQLException {
     private void updateWaystone(List<Location> locations) throws SQLException {
         STEMCraft.runLater(5, () -> {
             try {
+                List<String> allowedDimensionStringList = SMConfig.main().getStringList("waystones.allowedDimensions");
```
Comment (nomadjimbob) [inline src/main/java/com/stemcraft/feature/SMWaystones.java:235]: Cache this data `onEnabled` instead of calling every method (which could be a lot!). See https://github.com/STEMMechanics/STEMCraft-Core/blob/680d2c46b14a55f9288653c36b04b8bb6b6d2dee/src/main/java/com/stemcraft/feature/SMGraves.java#L27 for an example of how SMGraves does this

**Comment by nomadjimbob** [comment]
Thanks Project, just a few comments to fix up and it should be good to merge

File: src/main/java/com/stemcraft/feature/SMWaystones.java (hunk 1 above)
Comment (ProjectHSI) [reply src/main/java/com/stemcraft/feature/SMWaystones.java:235]: only problem with this is that it won't update on config changes

Comment (ProjectHSI) [reply src/main/java/com/stemcraft/feature/SMWaystones.java]: or does it reenable plugins on config reload?

**Comment by ProjectHSI** [comment]
fixed up

File: src/main/java/com/stemcraft/feature/SMWaystones.java [hunk 2]
```diff
@@ -47,6 +51,18 @@ protected Boolean onEnable() {
                 "under_block TEXT NOT NULL)").executeUpdate();
         });
 
+        if (!SMConfig.main().contains("waystones.worlds"))
+            SMConfig.main().set("waystones.worlds", new ArrayList<String>(), "Whitelist for waystone dimensions.");
```
Comment (nomadjimbob) [inline src/main/java/com/stemcraft/feature/SMWaystones.java:55]: `dimensions` listed here instead of `worlds`. Remove the full stop!

File: src/main/java/com/stemcraft/feature/SMWaystones.java [hunk 3]
```diff
@@ -47,6 +51,18 @@ protected Boolean onEnable() {
...
+        else {
+            List<String> worldsList = SMConfig.main().getStringList("graves.worlds");
```
Comment (nomadjimbob) [inline src/main/java/com/stemcraft/feature/SMWaystones.java:57]: incorrect config key!

**Review by nomadjimbob — COMMENTED** [review]
Couple of oversights!

File: src/main/java/com/stemcraft/feature/SMWaystones.java (hunk 3 above)
Comment (ProjectHSI) [reply src/main/java/com/stemcraft/feature/SMWaystones.java]: fixed

**Review by nomadjimbob — APPROVED** [review]
